### ISSUE TITLE
Diff to make Obsidian compile on OpenBSD

### ISSUE THREAD

**Issue by lea2501** [obsidian-level-maker/Obsidian#583]
Hi! here i leave a small diff to make Obsidian compile on OpenBSD 7.2 stable with same commands stated on COMPILING.md

Thanks in advance!

`diff --git a/source_files/zdbsp/tarray.h b/source_files/zdbsp/tarray.h
index 06f387e2a..54f9e883a 100644
--- a/source_files/zdbsp/tarray.h
+++ b/source_files/zdbsp/tarray.h
@@ -38,8 +38,10 @@
 #include <assert.h>
 #include <stdlib.h>
 #ifndef __APPLE__
+#ifndef __clang__
 #include <malloc.h>
 #endif
+#endif
 #include <new>

 // TArray -------------------------------------------------------------------`

**Comment by lea2501** [comment]
well, is not currently working, i got errors related to system files not being included

```
[ 84%] Building CXX object CMakeFiles/obsidian.dir/source_files/obsidian_main/csg_bsp.cc.o
In file included from /home/lea/src/Obsidian/source_files/obsidian_main/csg_bsp.cc:29:
In file included from /home/lea/src/Obsidian/source_files/obsidian_main/hdr_fltk.h:27:
In file included from /usr/local/include/FL/Fl.H:30:
/usr/local/include/FL/fl_utf8.h:62:12: fatal error: 'X11/Xlocale.h' file not found
#  include <X11/Xlocale.h>
           ^~~~~~~~~~~~~~~
1 error generated.
*** Error 1 in . (CMakeFiles/obsidian.dir/build.make:132 'CMakeFiles/obsidian.dir/source_files/obsidian_main/csg_bsp.cc.o': /usr/bin/c++ -DF...)
*** Error 2 in . (CMakeFiles/Makefile2:349 'CMakeFiles/obsidian.dir/all': /usr/bin/make -s -f CMakeFiles/obsidian.dir/build.make CMakeFiles/...)
*** Error 2 in /home/lea/src/Obsidian/build/dist (Makefile:136 'all': /usr/bin/make -s -f CMakeFiles/Makefile2 all)
```

**Comment by ghost** [comment]
I'll spin up an OpenBSD VM and see if I can sort it out. I've only tested the BSD portions via FreeBSD.

**Comment by ghost** [comment]
As of https://github.com/obsidian-level-maker/Obsidian/commit/a28d7efac4dbf983ff3abc7a160abab9483bd70c, OpenBSD compilation/execution should be good to go.
