### ISSUE TITLE
compilation error in source_files/fltk/FL/platform_types.h when compiling in OpenBSD

### ISSUE THREAD

**Issue by lea2501** [obsidian-level-maker/Obsidian#586]
After the last commit, when i try to compile in OpenBSD 7.2 stable, i get the following errors compiling source_files/fltk/FL/platform_types.h file:

```
[ 85%] Building CXX object CMakeFiles/obsidian.dir/source_files/obsidian_main/csg_bsp.cc.o
In file included from /home/lea/src/Obsidian/source_files/obsidian_main/csg_bsp.cc:29:
In file included from /home/lea/src/Obsidian/source_files/obsidian_main/hdr_fltk.h:54:
/usr/local/include/FL/Fl_Scroll.H:108:17: warning: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Wnon-c-typedef-for-linkage]
  typedef struct {
                ^
                 ScrollInfo
/usr/local/include/FL/Fl_Scroll.H:110:5: note: type is not C-compatible due to this member declaration
    typedef struct { int x,y,w,h; } Fl_Region_XYWH;
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/FL/Fl_Scroll.H:134:5: note: type is given name 'ScrollInfo' for linkage purposes by this typedef declaration
  } ScrollInfo;
    ^
In file included from /home/lea/src/Obsidian/source_files/obsidian_main/csg_bsp.cc:29:
In file included from /home/lea/src/Obsidian/source_files/obsidian_main/hdr_fltk.h:71:
In file included from /home/lea/src/Obsidian/source_files/fltk/FL/platform.H:32:
/home/lea/src/Obsidian/source_files/fltk/FL/platform_types.h:106:15: error: typedef redefinition with different types ('void *' vs 'Region' (aka '_XRegion *'))
typedef void *Fl_Region;
              ^
/usr/local/include/FL/x.H:56:16: note: previous definition is here
typedef Region Fl_Region;
               ^
In file included from /home/lea/src/Obsidian/source_files/obsidian_main/csg_bsp.cc:29:
In file included from /home/lea/src/Obsidian/source_files/obsidian_main/hdr_fltk.h:71:
In file included from /home/lea/src/Obsidian/source_files/fltk/FL/platform.H:32:
/home/lea/src/Obsidian/source_files/fltk/FL/platform_types.h:119:14: error: cannot combine with previous 'int' declaration specifier
typedef  int FL_SOCKET;
             ^
/usr/local/include/FL/Fl.H:54:20: note: expanded from macro 'FL_SOCKET'
# define FL_SOCKET int
                   ^
1 warning and 2 errors generated.
*** Error 1 in . (CMakeFiles/obsidian.dir/build.make:132 'CMakeFiles/obsidian.dir/source_files/obsidian_main/csg_bsp.cc.o': /usr/bin/c++ -DF...)
*** Error 2 in . (CMakeFiles/Makefile2:368 'CMakeFiles/obsidian.dir/all': /usr/bin/make -s -f CMakeFiles/obsidian.dir/build.make CMakeFiles/...)
*** Error 2 in /home/lea/src/Obsidian/build/dist (Makefile:136 'all': /usr/bin/make -s -f CMakeFiles/Makefile2 all)
```

The commands to build used:
```
$ cmake --preset dist
$ cmake --build --preset dist
```

The dependencies i have installed:
`doas pkg_add cmake gmake sdl2`

Operating system info:
```
$ uname -a
OpenBSD latitude5480.my.domain 7.2 GENERIC.MP#7 amd64
```

Thanks in advance!

**Comment by ghost** [comment]
I used the combo of 
cmake -B build
and 
cmake --build build -j# 
to compile and never encountered such an error. This was on a fresh OpenBSD 7.2 amd64 VM. I'm not sure what the cause of this error would be but I would try again with the above commands and see if it works.

**Comment by ghost** [comment]
I am unable to reproduce this error with either set of CMake instructions. I spun up a brand-new VM, and here is a complete record of the commands I used with success:

- Select X Windows System + xenodm X Windows autostart in OpenBSD installer

- Once logged in:
  - (from root prompt) pkg_add cmake git
  - (from user prompt) git clone https://github.com/obsidian-level-maker/obsidian
  - (from user prompt)  cd obsidian
  - (from user prompt)  cmake --preset dist
  - (from user prompt)  cmake --build --preset dist -j4

If you are able to isolate the problem and it is something we can fix in the repo, please let us know.
